[package]
name = "micast-broadcaster"
version = "0.1.13"
edition = "2018"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

memchr = "^2.5"

gst = { package = "gstreamer", git = "https://gitlab.freedesktop.org/gstreamer/gstreamer-rs" }
gst-base = { package = "gstreamer-base", git = "https://gitlab.freedesktop.org/gstreamer/gstreamer-rs" }
gst-audio = { package = "gstreamer-audio", git = "https://gitlab.freedesktop.org/gstreamer/gstreamer-rs" }
gst-video = { package = "gstreamer-video", git = "https://gitlab.freedesktop.org/gstreamer/gstreamer-rs" }
gst-controller = { package = "gstreamer-controller", git = "https://gitlab.freedesktop.org/gstreamer/gstreamer-rs" }
gst-net = { package = "gstreamer-net", git = "https://gitlab.freedesktop.org/gstreamer/gstreamer-rs" }

once_cell = "1.0"
parking_lot = "0.12"

anyhow = "1.0"
log = "0.4"

serde = { version = "1.0", features = ["derive"] }
quick-xml = { version = "0.23", features = [ "serialize" ] }
chrono = { version = "0.4", features = [ "serde" ] }

reqwest = { version = "0.11", features = ["blocking"]}
async-std = {version = "1.12", features = ["attributes", "tokio1"]}
futures = "0.3"

[dev-dependencies]
env_logger = "0.9"

[features]
default = ["v1_18"]
v1_20 = ["gst/v1_20"]
v1_18 = ["gst/v1_18"]