[package]
name = "micast-broadcaster"
version = "0.1.7"
edition = "2018"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

memchr = "^2.5"
gstreamer = { version = "^0.17", features = ["v1_16"] }
gstreamer-net = { version = "^0.17", features = ["v1_16"] }
gstreamer-controller = { version = "^0.17", features = ["v1_16"] }
glib = { version = "^0.14" }
anyhow = "1.0"
log = "0.4"

serde = { version = "1.0", features = ["derive"] }
quick-xml = { version = "0.22", features = [ "serialize" ] }
chrono = { version = "0.4", features = [ "serde" ] }

[dev-dependencies]
env_logger = "0.9"