[package]
name = "micast-broadcaster"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gstreamer = { version = "^0.17", features = ["v1_18"] }
gstreamer-net = { version = "^0.17", features = ["v1_18"] }
glib = { version = "^0.14" }
anyhow = "1.0"
log = "0.4"

[dev-dependencies]
env_logger = "0.9"