[package]
name = "micast-broadcaster"
version = "0.2.1"
edition = "2018"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

memchr = "^2.5"

anyhow = "1.0"
log = "0.4"

serde = { version = "1.0", features = ["derive"] }
quick-xml = { version = "0.23", features = [ "serialize" ] }
chrono = { version = "0.4", features = [ "serde" ] }
once_cell = "1.0"

reqwest = { version = "0.11", features = ["blocking"]}
async-std = {version = "1.12", features = ["attributes", "tokio1"]}
futures = "0.3"

[dev-dependencies]
env_logger = "0.9"
